default_config:

input_boolean:
  heater_on:
    name: Heater toggle
  cooler_on:
    name: Cooler toggle

input_number:
  room_temp:
    name: Room Temperature
    initial: 20
    min: 16
    max: 30
    step: .5
    icon: mdi:home-thermometer

  room_floor_temp:
    name: Room Floor Temperature
    initial: 20
    min: 16
    max: 30
    step: .5
    icon: mdi:thermometer

  outside_temp:
    name: Outside Temperature
    initial: 20
    min: 0
    max: 30
    step: .5
    icon: mdi:thermometer-lines

sensor:
  - platform: template
    sensors:
      room_temp:
        value_template: "{{ states.input_number.room_temp.state | int | round(1) }}"
        entity_id: input_number.room_temp

switch:
  - platform: template
    switches:
      heater:
        value_template: "{{ is_state_attr('switch.heater', 'sensor_state', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.heater
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.heater

      cooler:
        value_template: "{{ is_state_attr('switch.cooler', 'sensor_state', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.cooler
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.cooler

climate:
  - platform: dual_smart_thermostat
    name: Heat Cool Room
    heater: switch.heater
    cooler: switch.cooler
    target_sensor: sensor.room_temp
    min_temp: 15
    max_temp: 28
    ac_mode: false
    target_temp: 23
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool"
    away_temp: 16
    precision: 0.1

logger:
  default: error
  logs:
    custom_components.dual_smart_thermostat: debug